dist: trusty

language: node_js
node_js: "8.11.3"

addons:
  chrome: stable

branches:
  only:
    - master

before_install:
  - cd ng-app
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

script:
  - yarn test --watch false

cache:
  yarn: true
  directories:
    - ng-app/node_modules

notifications:
  email:
    on_failure: change
    on_success: change
