version: '3'

# Define the services/containers to be run
services:
  ng-app:
    build: ng-app
    ports:
      - "4200:4200"

  api:
    build: api
    ports:
      - "8009:8009"
    links:
      - db
    environment:
      - RUST_LOG=frunze_api=info

  db:
    image: mongo:3.2
    ports:
      - "27017:27017"
    # Use for development only if you'd like to store DB files in a known place on your host machine.
    volumes:
      - ./db/data-files:/data/db
      - ./db/preloaded:/data/preloaded
