[package]
name = "frunze_api"
version = "0.1.0"
authors = ["Aleh Zasypkin <aleh.zasypkin@gmail.com>"]

[dependencies]
ansi_term = "0.9.0"
docopt = "0.7.0"
env_logger = "0.4.1"
log = "0.3.6"
rustc-serialize = "0.3.22"
